# Generated by Django 4.0.6 on 2023-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBooth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booth',
            old_name='Introduction',
            new_name='introduction',
        ),
        migrations.AlterField(
            model_name='booth',
            name='club_picture',
            field=models.ImageField(default='/images/club_image/default_image.jpg', upload_to=''),
        ),
    ]
